alter session set "_ORACLE_SCRIPT" = true;



alter pluggable database KOD_PDB open;
-- Задание №1 --
SELECT name, open_mode FROM v$pdbs;
    SELECT pdb_name, pdb_id, status FROM SYS.dba_pdbs;

-- Задание №2 --
SELECT * FROM v$instance;

-- Задание №3 --
SELECT * FROM SYS.PRODUCT_COMPONENT_VERSION;

-- Задание №4 --
CREATE PLUGGABLE DATABASE KOD_PDB
ADMIN USER pdb_admin IDENTIFIED BY 123456
ROLES = (DBA)
FILE_NAME_CONVERT =('/u02/app/oracle/oradata/ORCL/pdbseed', '/u02/app/oracle/oradata/ORCL/KOD_PDB');

-- Задание №5 --
SELECT name, open_mode FROM v$pdbs;
SELECT name FROM v$pdbs;


-- Задание №6 (Это уже на PDB)
CREATE TABLESPACE TS_KOD
DATAFILE 'TS_PDB.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;

CREATE TEMPORARY TABLESPACE TS_KOD_TEMP
TEMPFILE 'TS_PDB_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M;

CREATE ROLE RL_PDB_KOD;
GRANT ALL PRIVILEGES TO RL_PDB_KOD;
GRANT CREATE SESSION TO RL_PDB_KOD;
COMMIT;

CREATE PROFILE PF_PDB_KOD LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 174
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

CREATE USER U1_KOD_PDB IDENTIFIED BY '123456'
DEFAULT TABLESPACE TS_KOD
TEMPORARY TABLESPACE TS_KOD_TEMP
PROFILE PF_PDB_KOD
ACCOUNT UNLOCK;

GRANT RL_PDB_KOD TO U1_KOD_PDB;
-- Задание №7 --
create  table  KOD_TABLE (
    Name nvarchar2(20),
    Age number
);



INSERT INTO KOD_TABLE (Name, Age) VALUES ('Олег', 19);
INSERT INTO KOD_TABLE (Name, Age) VALUES ('Илья', 19);
INSERT INTO KOD_TABLE (Name, Age) VALUES ('Кирилл', 20);
INSERT INTO KOD_TABLE (Name, Age) VALUES ('Антон', 20);

-- Задание №8 --

SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM USER_TABLESPACES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_ROLE_PRIVS ORDER BY GRANTEE;
SELECT * FROM DBA_PROFILES ORDER BY PROFILE;
SELECT * FROM DBA_USERS ORDER BY USERNAME;
SELECT USERNAME, GRANTED_ROLE FROM DBA_USERS JOIN DBA_ROLE_PRIVS ON USERNAME = GRANTEE ORDER BY USERNAME;

-- Задани 9 --

-- В файле

-- Задание №11
SELECT * FROM v$session WHERE username IS NOT NULL;

-- Задание №12
SELECT *  FROM DBA_DATA_FILES;

-- Задание №13
ALTER PLUGGABLE DATABASE KOD_PDB CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE  KOD_PDB ;
DROP USER C##KOD;



DROP TABLE  KOD_TABLE;