-- Задани 1 --
SELECT * FROM DBA_TABLESPACES;
-- Задани 2 --
CREATE TABLESPACE KOD_QDATA
DATAFILE 'KOD_QDATA.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M
MAXSIZE 20M
OFFLINE;

ALTER TABLESPACE  KOD_QDATA ONLINE;

DROP TABLESPACE KOD_QDATA INCLUDING CONTENTS AND DATAFILES;


CREATE TABLE KOD_T1
(
    Id number(5) primary key,
    Name nvarchar2(20)
)TABLESPACE KOD_QDATA;
INSERT INTO  KOD_T1 (Id, Name) VALUES (1, 'Oleg');
INSERT INTO  KOD_T1 (Id, Name) VALUES (2, 'Anton');
INSERT INTO  KOD_T1 (Id, Name) VALUES (3, 'Kirill');
INSERT INTO  KOD_T1 (Id, Name) VALUES (4, 'Vlados');

drop  table KOD_T1;
-- Задание 3 --
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KOD_QDATA';
-- Задание 4 --
DROP TABLE KOD_T1 purge ;
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KOD_QDATA';
SELECT * FROM USER_RECYCLEBIN;
COMMIT;
-- Задание 5 --
FLASHBACK TABLE  KOD_T1 TO  BEFORE DROP;
SELECT * FROM  KOD_T1;
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KOD_QDATA';
-- Задание 6 --
BEGIN
FOR k in 5..10000
    LOOP
    INSERT INTO KOD_T1 (Id) VALUES (k);
    end loop;
    COMMIT;
END;
SELECT * FROM  KOD_T1;
-- Задание 7 --
SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES, BLOCKS, EXTENTS, BUFFER_POOL FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'KOD_QDATA';
SELECT * FROM USER_EXTENTS WHERE TABLESPACE_NAME = 'KOD_QDATA';
-- Задание 8 --
DROP TABLESPACE KOD_QDATA INCLUDING CONTENTS AND DATAFILES;
-- Задание 9 --
SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;
-- Задание 10 --
SELECT * FROM V$LOGFILE;
-- Задание 11 --
ALTER SYSTEM SWITCH LOGFILE;
SELECT GROUP#, STATUS, MEMBERS FROM V$LOG;
-- Задание 12 --
ALTER DATABASE  ADD LOGFILE GROUP 4 '/u04/app/oracle/redo/redo004.log'
SIZE  50M BLOCKSIZE 512;
ALTER  DATABASE  ADD LOGFILE MEMBER '/u04/app/oracle/redo/redo0041.log' TO GROUP 4;
ALTER  DATABASE  ADD LOGFILE MEMBER '/u04/app/oracle/redo/redo0042.log' TO GROUP 4;
SELECT * FROM V$LOG;
-- Задание 13 --
ALTER DATABASE DROP LOGFILE GROUP 4;
-- Задание 14 --
SELECT NAME, LOG_MODE FROM V$DATABASE;
SELECT INSTANCE_NAME, ARCHIVER, ACTIVE_STATE FROM V$INSTANCE;
-- Задание 15 --
-- Задание 16 --
SELECT NAME, LOG_MODE FROM V$DATABASE;
-- Задание 17 --
SELECT * FROM V$LOG;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1 ='LOCATION=/u04/app/oracle/redo/Archive';
ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V$ARCHIVED_LOG;
-- Задание 18 --
select name, log_mode from v$database;
-- Задание 19 --
SELECT * FROM V$CONTROLFILE;

-- Задане №20 (В консоли)
-- В консоли: SHOW PARAMETER CONTROL;

-- Задание №21 (В консоли)
-- В консоли: SHOW PARAMERER spfile;
-- Задание 22 --
CREATE PFILE = 'KOD_PFILE.ora' FROM SPFILE;
-- Задание 23 --
SELECT * FROM V$PWFILE_USERS;
-- Задание 24 --
SELECT * FROM V$DIAG_INFO;