CREATE  TABLESPACE  TS_KOD
    DATAFILE 'C:\TS_KOD.dbf'
    size 7M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;

CREATE TEMPORARY TABLESPACE  TS_KOD_TEMP
    TEMPFILE 'C:\TS_KOD_TMP.dbf'
    size 5M
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;

alter session set "_ORACLE_SCRIPT" = true;


CREATE ROLE RL_KODCORE;
GRANT CREATE SESSION, CREATE TABLE, DROP ANY TABLE,
    CREATE VIEW, DROP ANY VIEW,
    CREATE PROCEDURE, DROP ANY PROCEDURE TO RL_KODCORE;
COMMIT;

SET ROLE RL_KODCORE IDENTIFIED BY RL_KODCORE;

SELECT * FROM "PUBLIC".DBA_ROLES WHERE ROLE = 'RL_KODCORE';
SELECT * FROM DBA_SYS_PRIVS WHERE  GRANTEE = 'RL_KODCORE';


CREATE PROFILE PF_KODCORE LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;



SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_KODCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

ALTER USER KODCORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_KOD
TEMPORARY TABLESPACE TS_KOD_TEMP
PROFILE PF_KODCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE;

GRANT RL_KODCORE TO KODCORE;

CREATE TABLESPACE KOD_QDATA
DATAFILE 'C:\Labs\Databases\Lab2\GKV_QDATA.dbf'
SIZE 10M
AUTOEXTEND ON NEXT 5M
MAXSIZE 20M
OFFLINE;

ALTER TABLESPACE KOD_QDATA ONLINE;
ALTER USER KODCORE QUOTA 2M ON KOD_QDATA;

INSERT INTO KODCORE.Products (NameProduct, Cost) VALUES ('Яйцо', 10);
INSERT INTO KODCORE.Products (NameProduct, Cost) VALUES ('Дыня', 1);
INSERT INTO KODCORE.Products (NameProduct, Cost) VALUES ('Хлеб', 20);
commit ;